# 

version: "3.0"

services: 
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: tester
      MYSQL_PASSWORD: test
  
  api:
    depends_on: 
      - db
    build: 
      context: ..
      dockerfile: dockerfiles-dev/Dockerfile.hotreload
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ../src:/usr/app/src
      # - nodemodules:/usr/app/src/node_modules
    restart: always
    environment:
      RDS_HOSTNAME: db

volumes: 
  # nodemodules: {}
  db_data: {}
